In [1]:
import numpy as np
from agent_gfe import GFEAgent
from agent_gfe_param import generate_gfe_params
from environment import Environment
from environment_param import a, b, d

time_horizon = 3
A, B, B_c, C, D, D_c, U = generate_gfe_params(c=2, alpha=0.9)
D_c = np.array([0.5, 0.5])
agent = GFEAgent(A, B, B_c, C, D, D_c, U, time_horizon)
environment = Environment(a, b, d)

agent.infer()
agent.print_beliefs()

Iteration 0
Iteration 0
[[0.125 0.125]
 [0.125 0.125]
 [0.125 0.125]
 [0.125 0.125]]
[[0.5 0.5]
 [0.  0. ]
 [0.  0. ]
 [0.  0. ]]

Iteration 1
[[0.125 0.125]
 [0.125 0.125]
 [0.125 0.125]
 [0.125 0.125]]
[[0.5 0.5]
 [0.  0. ]
 [0.  0. ]
 [0.  0. ]]

Iteration 2
[[0.125 0.125]
 [0.125 0.125]
 [0.125 0.125]
 [0.125 0.125]]
[[0.5 0.5]
 [0.  0. ]
 [0.  0. ]
 [0.  0. ]]

Iteration 3
[[0.125 0.125]
 [0.125 0.125]
 [0.125 0.125]
 [0.125 0.125]]
[[0.5 0.5]
 [0.  0. ]
 [0.  0. ]
 [0.  0. ]]

Iteration 4
[[0.125 0.125]
 [0.125 0.125]
 [0.125 0.125]
 [0.125 0.125]]
[[0.5 0.5]
 [0.  0. ]
 [0.  0. ]
 [0.  0. ]]

Iteration 5
[[0.125 0.125]
 [0.125 0.125]
 [0.125 0.125]
 [0.125 0.125]]
[[0.5 0.5]
 [0.  0. ]
 [0.  0. ]
 [0.  0. ]]

Iteration 6
[[0.125 0.125]
 [0.125 0.125]
 [0.125 0.125]
 [0.125 0.125]]
[[0.5 0.5]
 [0.  0. ]
 [0.  0. ]
 [0.  0. ]]

Iteration 7
[[0.125 0.125]
 [0.125 0.125]
 [0.125 0.125]
 [0.125 0.125]]
[[0.5 0.5]
 [0.  0. ]
 [0.  0. ]
 [0.  0. ]]

Iteration 8
[[0.125 0.125]
 [0.125 0