In [1]:
import numpy as np
from utils import optimize
from agent_gfe_param import generate_gfe_params
np.set_printoptions(precision=30)

A, B, B_c, C, D, D_c, U = generate_gfe_params(c=2, alpha=0.9)
state_context_belief = np.array([[0.125, 0.125],
                                 [0.125, 0.125],
                                 [0.125, 0.125],
                                 [0.125, 0.125]])
rightward_context_message = np.array([0.9, 0.1])
upward_context_messages = np.array([[0.5, 0.5],
                                    [0.5, 0.5],
                                    [0.5, 0.5]])
rightward_state_message = np.array([0.25, 0.25, 0.25, 0.25])
#rightward_state_message = np.array([1, 0, 0, 0])
leftward_state_message = np.array([0.25, 0.25, 0.25, 0.25])

q_s_c = optimize(
    A,
    C,
    state_context_belief,
    rightward_context_message,
    upward_context_messages,
    rightward_state_message,
    leftward_state_message
)
print("context_belief", np.einsum('ij->j', q_s_c))

Iteration 0
[[0.125 0.125]
 [0.125 0.125]
 [0.125 0.125]
 [0.125 0.125]]
[[0.08613646697083988   0.009570718552315543 ]
 [0.17227293394167972   0.019141437104631082 ]
 [0.6164622395346101    0.0027920399503189135]
 [0.02512835955287022   0.06849580439273446  ]]

Iteration 1
[[0.125 0.125]
 [0.125 0.125]
 [0.125 0.125]
 [0.125 0.125]]
[[0.08613646697083988   0.009570718552315543 ]
 [0.17227293394167972   0.019141437104631082 ]
 [0.6164622395346101    0.0027920399503189135]
 [0.02512835955287022   0.06849580439273446  ]]

Iteration 2
[[0.125 0.125]
 [0.125 0.125]
 [0.125 0.125]
 [0.125 0.125]]
[[0.08613646697083988   0.009570718552315543 ]
 [0.17227293394167972   0.019141437104631082 ]
 [0.6164622395346101    0.0027920399503189135]
 [0.02512835955287022   0.06849580439273446  ]]

Iteration 3
[[0.12500000186264515 0.125              ]
 [0.125               0.125              ]
 [0.125               0.125              ]
 [0.125               0.125              ]]
[[0.08613646639049488   0.